AcademyF_Leonardo_Sanna_MVC.MVC/Controllers/MenuController.cs
using AcademyF_Leonardo_Sanna_MVC.Core.Business;
using AcademyF_Leonardo_Sanna_MVC.MVC.Helper;
using AcademyF_Leonardo_Sanna_MVC.MVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AcademyF_Leonardo_Sanna_MVC.MVC.Controllers
{
    [Authorize]
    public class MenuController : Controller
    {
        IBusinessLayer BL;
        public MenuController(IBusinessLayer bl)
        {
            BL = bl;
        }
        public IActionResult Index()
        {
            var menu = BL.GetAllMenu();
            List<MenuViewModel> menuvm = new List<MenuViewModel>();
            foreach(var item in menu)
            {
                menuvm.Add(item.ToMenuVM());
            }
            return View(menuvm);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var piatto = BL.GetAllMenu().Find(m=>m.id == id);
            return View(piatto);
        }

    }
}

AcademyF_Leonardo_Sanna_MVC.MVC/Controllers/PiattiController.cs
using AcademyF_Leonardo_Sanna_MVC.Core.Business;
using AcademyF_Leonardo_Sanna_MVC.MVC.Helper;
using AcademyF_Leonardo_Sanna_MVC.MVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AcademyF_Leonardo_Sanna_MVC.MVC.Controllers
{
    [Authorize]
    public class PiattiController : Controller
    {
        private readonly IBusinessLayer BL;

        public PiattiController(IBusinessLayer bl)
        {
            BL = bl;
        }

        public IActionResult Index()
        {
            var piatti = BL.GetAllPiatti();
            List<PiattoViewModel> piattivm = new List<PiattoViewModel>();
            foreach (var piatto in piatti)
            {
                piattivm.Add(piatto.ToPiattoVM());
            }
            return View(piattivm);
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            var piatto = BL.GetPiatto(id).ToPiattoVM();
            return View(piatto);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(PiattoViewModel piattovm)
        {
            if (piattovm == null)
                return View("Error");
            if (BL.AddPiatto(piattovm.ToPiatto()))
            {
                ViewBag.Messaggio = "Piatto Inserito Correttamente!";
                return View();
            }
            else
            {
                ViewBag.Messaggio = "Piatto Non Inserito!";
                return View();
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var corso = BL.GetAllPiatti().FirstOrDefault(c => c.Id== id);
            var corsoVM = corso.ToPiattoVM();
            return View(corsoVM);
        }
        [HttpPost]
        public IActionResult Delete(PiattoViewModel piattovm)
        {
            var piatto = piattovm.ToPiatto();
            var flag = BL.RemovePiatto(piatto);
            if (flag)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewBag.MessaggioErrore = "cancellazione non eseguita";
                return View();
            }
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var piatto = BL.GetAllPiatti().FirstOrDefault(c => c.Id == id);
            var corsoVM = piatto.ToPiattoVM();
            return View(corsoVM);
        }
        [HttpPost]
        public IActionResult Edit(PiattoViewModel piattovm)
        {
            if (ModelState.IsValid)
            {
                var corso = piattovm.ToPiatto();
                var flag = BL.UpdatePiatto(piattovm.ToPiatto());
                if (flag)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.MessaggioErrore = "Non è stato possibile la modifica";
                    return View();
                }
            }
            return View(piattovm);
        }

        public IActionResult DisassegnaPiatto(int id)
        {
            var piatto = BL.GetPiatto(id);
            var corsoVM = piatto.ToPiattoVM();
            return View(corsoVM);
        }

        [HttpPost]
        public IActionResult DisassegnaPiatto(PiattoViewModel piattovm)
        {
            var piatto = BL.GetPiatto(piattovm.Id);
            piatto.MenuId = null;
            piatto.Menu = null;
            BL.UpdatePiatto(piatto);
            return View();
        }

        public IActionResult AssegnaPiatto(int id)
        {
            var piatto = BL.GetPiatto(id);
            var corsoVM = piatto.ToPiattoVM();
            ViewBag.Menu = BL.GetAllMenu();
            return View(corsoVM);
        }

        [HttpPost]
        public IActionResult AssegnaPiatto(PiattoViewModel piattovm)
        {
            var piatto = BL.GetPiatto(piattovm.Id);
            piatto.MenuId = piattovm.MenuId;
            piatto.Menu = BL.GetAllMenu().Find(m=>m.id==piattovm.Id);
            BL.UpdatePiatto(piatto);
            return View("Piatti/Index");
        }
    }
}

AcademyF_Leonardo_Sanna_MVC.MVC/Controllers/UtentiController.cs
using AcademyF_Leonardo_Sanna_MVC.Core.Business;
using AcademyF_Leonardo_Sanna_MVC.MVC.Helper;
using AcademyF_Leonardo_Sanna_MVC.MVC.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AcademyF_Leonardo_Sanna_MVC.MVC.Controllers
{
    public class UtentiController : Controller
    {
        private readonly IBusinessLayer BL;

        public UtentiController(IBusinessLayer bl)
        {
            BL = bl;
        }
        // GET: UtentiController
        public ActionResult Login(string url = "/")
        {
            return View(new UtenteViewModel() { ReturnUrl = url });
        }
        [HttpPost]
        public async Task<ActionResult> Login(UtenteViewModel utenteVM)
        {
            if (utenteVM == null)
            {
                return View();
            }

            var utente = BL.GetAccount(utenteVM.Username);
            if (utente != null && ModelState.IsValid)
            {
                if (utente.Password == utenteVM.Password)
                {
                    //l'utente è "autenticato"
                    var claim = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, utente.Username),
                        new Claim(ClaimTypes.Role, utente.Ruolo.ToString()),
                    };

                    var properties = new AuthenticationProperties
                    {
                        RedirectUri = utenteVM.ReturnUrl,
                        ExpiresUtc = DateTimeOffset.UtcNow.AddHours(1) // logout dopo un'ora di inattività
                    };

                    var claimIdentity = new ClaimsIdentity(claim, CookieAuthenticationDefaults.AuthenticationScheme);

                    await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(claimIdentity),
                        properties
                        );
                    return Redirect("/");

                }
                else
                {
                    ModelState.AddModelError(nameof(utenteVM.Password), "Password Errata");
                    return View(utenteVM);
                }
            }
            else
            {
                return View(utenteVM);
            }
            return View();
        }
        public async Task<IActionResult> LogoutAsync()
        {
            await HttpContext.SignOutAsync();
            return Redirect("/");
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> RegisterAsync(UtenteViewModel utente)
        {
            if (utente == null)
            {
                ViewBag.MessaggioErrore = "Utente data invalid";
                return View("ErroriDiBusiness");
            }
            if (ModelState.IsValid)
            {
                BL.AddUtente(utente.ToUtente());
                return await Login(utente);
            }
            else
                return View(utente);
        }
    }
}

AcademyF_Leonardo_Sanna_MVC.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ristorantebellino</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AcademyF_Leonardo_Sanna_MVC.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <img src="media/images/bellino.jpg" alt="Bellino" height="70px">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> </a>
                </img>
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Menu" asp-action="Index">Menu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Piatti" asp-action="Index">Piatti</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contatti">Contatti</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
                @if (User.Identity.IsAuthenticated)
                {
                    var name = ((System.Security.Claims.ClaimsIdentity)User.Identity).Claims.First(x => x.Type == System.Security.Claims.ClaimTypes.Name).Value;
                    <strong style="margin-right:5px">Benvenut* @name</strong>
                    <a asp-controller="Utenti" asp-action="Logout">Log out</a>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Leonardo_Sanna - <a href="https://github.com/SannaLeo/" target="_blank">LS</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>